### PR TITLE
Fix: Update viewing inventory on dirty title or dirty rows

### LINKED ISSUE #2469: ChestGui#setTitle causes ChestGui#update to fail
After setting a new title for a GUI, the ChestGui#update method doesn't work anymore.
As an example, use the following test class:

```
public class TestPage {
    public static void openTestPage(Player player) {
        ChestGui gui = new ChestGui(6, "Page 1");
        gui.setOnGlobalClick(event -> event.setCancelled(true));
        gui.setOnGlobalDrag(event -> event.setCancelled(true));

        PaginatedPane pages = new PaginatedPane(0, 0, 9, 5);
        OutlinePane page1 = new OutlinePane(0, 0, 9, 5);
        page1.addItem(new GuiItem(new ItemStack(Material.DIAMOND)));
        pages.addPage(page1);

        OutlinePane page2 = new OutlinePane(0, 0, 9, 5);
        page2.addItem(new GuiItem(new ItemStack(Material.GOLD_INGOT)));
        pages.addPage(page2);

        gui.addPane(pages);

        StaticPane navigation = new StaticPane(0, 5, 9, 1);
        navigation.addItem(new GuiItem(new ItemStack(Material.RED_WOOL), event ->
                openPage(gui, pages, pages.getPage() - 1)), 0, 0);

        navigation.addItem(new GuiItem(new ItemStack(Material.GREEN_WOOL), event ->
                openPage(gui, pages, pages.getPage() + 1)), 8, 0);

        navigation.addItem(new GuiItem(new ItemStack(Material.BARRIER), event ->
                event.getWhoClicked().closeInventory()), 4, 0);

        gui.addPane(navigation);

        gui.show(player);
    }

    private static void openPage(ChestGui gui, PaginatedPane pages, int page) {
        if (page < 0) {
            page = 0;
        } else if (page >= pages.getPages()) {
            page = pages.getPages() - 1;
        }

        pages.setPage(page);

        // Uncomment this line:
        // gui.setTitle("Page " + (page + 1));
        gui.update();
    }
}
```

Without setting the title in the openPage method, you can switch between two pages with the red and green wool. If you now uncomment the gui.setTitle line, changing the page doesn't work anymore.

Tested on Paper version 1.21.10-82-main@1e67ca8 with IF 0.11.5

### PR DESCRIPTION
**Pull request by JZalaOz**
Fixes #2469

### CODE REVIEW

File: IF/src/main/java/com/github/stefvanschie/inventoryframework/gui/type/ChestGui.java [hunk 1]
```diff
@@ -113,9 +113,14 @@ public void update() {
         super.updating = true;
 
         if (isDirty() || dirtyRows) {
+            Inventory oldInventory = this.inventory;
             this.inventory = createInventory();
             this.dirtyRows = false;
 
+            for (HumanEntity viewer : new ArrayList<>(oldInventory.getViewers())) {
```
Comment (stefvanschie) [inline IF/src/main/java/com/github/stefvanschie/inventoryframework/gui/type/ChestGui.java]: `oldInventory.getViewers()` might cause a `NullPointerException` when the inventory is shown for the first time, when `this.inventory` is `null`. Please add a guard against this.

**Review by stefvanschie — CHANGES_REQUESTED** [review]
Thank you for your pull request. Could you address the comments I added to this review? Otherwise this might introduce a regression.
